AllenNeuralDynamics/aind-metadata-mapper

- .github/workflows/tag_and_publish.yml
> ci: modifies workflow to enable publishing to PyPI

- examples/bergamo_session.py
- src/aind_metadata_mapper/bergamo/session.py
- Adds example for using the bergamo etl class
> feat: adds example for bergamo session

- .github/workflows/tag_and_publish.yml
- Sets SERVICE_TOKEN from secrets for update_badges job
> fix: sets token for update_badges job in actions workflows

- src/aind_metadata_mapper/mesoscope/session.py
- tests/test_mesoscope.py
- Adds unit tests for full coverage
- Pydantic should validate paths. Removed checks on strings
> feat: adds unit tests for full coverage

- pyproject.toml
- Adds requests to list of dependencies
> ci: add requests to dependencies

- src/aind_metadata_mapper/gather_metadata.py
- tests/resources/gather_metadata_job/example_funding_multiple_response.json
- tests/resources/gather_metadata_job/example_funding_response.json
- tests/test_gather_metadata.py
- Updates gather_metadata to align with latest changes in aind-data-transfer
> feat: updates gather metadata

- pyproject.toml
> decreases coverage to 80%

- src/aind_metadata_mapper/gather_metadata.py
- tests/resources/gather_metadata_job/metadata_files/acquisition.json
- tests/resources/gather_metadata_job/metadata_files/instrument.json
- tests/resources/gather_metadata_job/metadata_files/rig.json
- tests/resources/gather_metadata_job/metadata_files/session.json
- tests/test_gather_metadata.py
Closes #58
- Adds option for user to define directory of pre-compiled metadata files
- Adds 4 json files in test resources
> Feat 58 metadata dir

- src/aind_metadata_mapper/gather_metadata.py
- tests/test_gather_metadata.py
- Catches validation errors when building the Metadata object
> fix: catches validation error

- src/aind_metadata_mapper/gather_metadata.py
- tests/test_gather_metadata.py
- Fixes issue with metadata not writing out _id field alias
> fix: writes correct id field

- src/aind_metadata_mapper/gather_metadata.py
- tests/test_gather_metadata.py
- tests/test_mesoscope/test_session.py
- hot fixes issue with accessing json in response
> Hot fix response json

- src/aind_metadata_mapper/bruker/session.py
- tests/test_bruker/test_session.py
- tests/test_mesoscope/test_session.py
> Hot Fix 72 mri ingest

- src/aind_metadata_mapper/bruker/session.py
- src/aind_metadata_mapper/gather_metadata.py
- tests/test_gather_metadata.py
- tests/test_mesoscope/test_session.py
- Patches issue with GatherMetadata failing due to unhashable type error
> Hot fix gather metadata

- src/aind_metadata_mapper/bergamo/session.py
- src/aind_metadata_mapper/bruker/session.py
- src/aind_metadata_mapper/core.py
- src/aind_metadata_mapper/dynamic_routing/mvr_rig.py
- src/aind_metadata_mapper/dynamic_routing/neuropixels_rig.py
- src/aind_metadata_mapper/fip/session.py
- src/aind_metadata_mapper/gather_metadata.py
- src/aind_metadata_mapper/mesoscope/session.py
- src/aind_metadata_mapper/open_ephys/camstim_ephys_session.py
- src/aind_metadata_mapper/open_ephys/utils/behavior_utils.py
- src/aind_metadata_mapper/open_ephys/utils/constants.py
- src/aind_metadata_mapper/open_ephys/utils/naming_utils.py
- src/aind_metadata_mapper/open_ephys/utils/pkl_utils.py
- src/aind_metadata_mapper/open_ephys/utils/stim_utils.py
- src/aind_metadata_mapper/open_ephys/utils/sync_utils.py
- src/aind_metadata_mapper/smartspim/acquisition.py
- src/aind_metadata_mapper/smartspim/utils.py
- src/aind_metadata_mapper/stimulus/camstim.py
> Test stim epoch changes

- pyproject.toml
- src/aind_metadata_mapper/bergamo/models.py
- src/aind_metadata_mapper/bergamo/session.py
- src/aind_metadata_mapper/bruker/models.py
- src/aind_metadata_mapper/bruker/session.py
- src/aind_metadata_mapper/fip/models.py
- src/aind_metadata_mapper/fip/session.py
- src/aind_metadata_mapper/mesoscope/models.py
- src/aind_metadata_mapper/mesoscope/session.py
- src/aind_metadata_mapper/smartspim/acquisition.py
- src/aind_metadata_mapper/smartspim/models.py
closes #96 
This PR:
- adds job_settings_name literal to each JobSettings class
- moves JobSettings to models.py for each package
- removes unused pytz dependency
- moves numpy and pandas dependencies to respective packages in pyproject.toml
> Feat 96 literals

- src/aind_metadata_mapper/gather_metadata.py
- tests/integration/bergamo/session.py
- tests/test_gather_metadata.py
> adds SessionSettings

- src/aind_metadata_mapper/core.py
- src/aind_metadata_mapper/gather_metadata.py
- src/aind_metadata_mapper/models.py
- tests/test_gather_metadata.py
> creates models module for gather metadata Settings

- pyproject.toml
> adds python 3.9 req for optional packages

- src/aind_metadata_mapper/__init__.py
- src/aind_metadata_mapper/models.py
Closes #130 
- Adds useful field to allow the gather metadata job settings to be used in a tagged Union
> feat: adds literal field to gather metadata settings

- pyproject.toml
- tests/resources/bergamo/session.json
> feat: adds upper bound to pydantic

- src/aind_metadata_mapper/__init__.py
- src/aind_metadata_mapper/core.py
- src/aind_metadata_mapper/gather_metadata.py
- src/aind_metadata_mapper/models.py
Closes #139
Patches issue with using PurePosixPath objects.
> Release v0.17.1

- pyproject.toml
> build: unpins aind-data-schema

- src/aind_metadata_mapper/core_models.py
> Allow extra fields on deserialization of BaseJobSettings

- src/aind_metadata_mapper/models.py
> fix: use extra allow in settings

- docs/source/conf.py
- src/aind_metadata_mapper/bruker/models.py
- src/aind_metadata_mapper/bruker/session.py
- src/aind_metadata_mapper/mesoscope/session.py
- src/aind_metadata_mapper/models.py
- src/aind_metadata_mapper/open_ephys/camstim_ephys_session.py
- src/aind_metadata_mapper/open_ephys/models.py
- src/aind_metadata_mapper/smartspim/models.py
- src/aind_metadata_mapper/stimulus/camstim.py
- src/aind_metadata_mapper/u19/models.py
- src/aind_metadata_mapper/u19/procedures.py
- tests/integration/bergamo/session.py
- tests/test_U19/test_procedures.py
- tests/test_bergamo/test_session.py
- tests/test_bruker/test_session.py
- tests/test_dynamic_routing/test_mvr_rig.py
- tests/test_dynamic_routing/test_sync_rig.py
- tests/test_open_ephys/test_rig.py
- tests/test_open_ephys/test_utils/test_stim_utils.py
closes #173 
Renames the U19Etl class to a more generic name.
> rename u19 etl

- pyproject.toml
Closes #203 
- Updates min supported version of aind-data-schema to v1.2.0
- Removes upper bound of pydantic
- Updates min supported python version
> build: update pydantic and aind-data-schema versions

- src/aind_metadata_mapper/gather_metadata.py
- tests/test_gather_metadata.py
Closes #211 
- Attaches the project_name to the data_description contents
> fix: adds project_name to data_description

- src/aind_metadata_mapper/gather_metadata.py
- src/aind_metadata_mapper/models.py
- tests/resources/gather_metadata_job/metadata_files/quality_control.json
- tests/test_gather_metadata.py
Closes #229
- Add quality_control metadata to list of stuff in gather_metadata_job
> feat: adds qc to gather_metadata_job

- .readthedocs.yaml
> docs: adds sphinx config to .readthedocs.yaml

- src/aind_metadata_mapper/__init__.py
- src/aind_metadata_mapper/open_ephys/utils/pkl_utils.py
- src/aind_metadata_mapper/stimulus/camstim.py
- tests/test_mesoscope/test_session.py
- tests/test_open_ephys/test_utils/test_pkl_utils.py
- tests/test_stimulus/test_camstim.py
- Remove mTrain call to get regimen
> Release v0.23.2

- pyproject.toml
- src/aind_metadata_mapper/gather_metadata.py
- src/aind_metadata_mapper/models.py
- tests/test_gather_metadata.py
- Adds location_map field to allow the s3_location to be dependent on the metadata_status
> feat: adds location map to handle metadata_status

- src/aind_metadata_mapper/__init__.py
- src/aind_metadata_mapper/models.py
* patches issue with aind-data-schema dependency
> Release v0.24.1 (#256)

- src/aind_metadata_mapper/mesoscope/session.py
- src/aind_metadata_mapper/open_ephys/utils/stim_utils.py
- src/aind_metadata_mapper/stimulus/camstim.py
- tests/test_mesoscope/test_session.py
- tests/test_open_ephys/test_utils/test_stim_utils.py
Adds new functions to align ophys and ephys photodiodes using different methods so that we don't get weird misalignment in ophys.
> Bug fix/ophys timing vsyncs

- docs/source/Contributing.rst
- docs/source/UserGuide.rst
closes #275 
This PR improves documentation for this repository:
- More instructions in contributing for JobSettings and ETL structure
- Removes data-transfer instructions
- Adds instructions on the gather metadata job
> docs: gather metadata instructions, cleanup

- docs/source/Contributing.rst
- docs/source/UserGuide.rst
- docs/source/aind_metadata_mapper.pavlovian_behavior.rst
fixes some formatting from #275 
adds pavlovian behavior docs in src automatically generated docs
> formatting fixes in docs

- .github/workflows/publish_v1.yml
- docs/source/UserGuide.rst
- pyproject.toml
- src/aind_metadata_mapper/gather_processing_job.py
- tests/test_gather_processing_job.py
- tests/test_models.py
Closes #356 
- Updates UserGuide
- Adds workflow to publish a docker image whenever the release-v1.0.0 branch is updated
- Adds job to validate and write processing metadata
> feat: adds hook to generate processing.json file
