examples/bergamo_session.py, src/aind_metadata_mapper/bergamo/session.py, src/aind_metadata_mapper/core.py, tests/test_bergamo.py, tests/test_legacy_core.py
Closes #16 
- Updates the interface so that a user defines the job using a pydantic BaseSettings class. The user will need to implement a run_job method
- Adds an extra unit test module for legacy functions that used to be covered by the old bergamo etl tests
- In the future, all jobs should be implemented like:
```python
job_settings_json = user_settings.model_dump_json()
etl_job = BergamoEtl(job_settings=job_settings_json)
job_response = etl_job.run_job()
```
=> feat: refactors bergamo mapper

pyproject.toml, src/aind_metadata_mapper/bergamo/session.py, src/aind_metadata_mapper/ephys/session.py, src/aind_metadata_mapper/fib/session.py, src/aind_metadata_mapper/mesoscope/session.py, tests/resources/bergamo/expected_session.json, tests/resources/ephys/ephys_session.json, tests/resources/fib/000000_ophys_session.json, tests/resources/mesoscope/expected_session.json, tests/test_bergamo.py, tests/test_ephys.py, tests/test_fib.py, tests/test_mesoscope.py
Closes #33
- Updates version of aind-data-schema to 0.33.3
- Separating the code out from this PR: https://github.com/AllenNeuralDynamics/aind-metadata-mapper/pull/38
=> Feat 33 schema version

src/aind_metadata_mapper/gather_metadata.py, tests/test_gather_metadata.py
Closes #70 
- Removes assertion that procedures metadata needs to be valid
- Adds warning if procedures metadata is not valid
=> feat: removes restriction on procedures metadata

README.md, pyproject.toml, scripts/singularity_build.def
Closes #80 
- Breaks up dependencies so users that only need to run the bergamo etl job don't have to install wavpack-numcodecs, which needs to be done outside of pip
=> build: splits up dependencies into opitonal deps

src/aind_metadata_mapper/gather_metadata.py, tests/test_gather_metadata.py
- Patches a small issue where the smartspim acquisition is saved as a string instead of a dict
=> fix: smartspim acquisition str to dict

src/aind_metadata_mapper/stimulus/camstim.py
I changed the usage of the right key name in the stim table. Previously, was using `stim_type` to check if the stimulus was a movie or image set. However, `stim_type` should probably always be VisualStimulation. `stim_name` is more likely to contain the useful information.
=> change stim_type key to stim_name for listing stim params

.github/workflows/run_dev_tests.yml, pyproject.toml
closes #112 
This PR:
- requires python 3.8 to install aind-metadata-mapper
- requires python 3.9 to install aind-metadata-mapper[dev]
- adds 3.9 to python matrix in github actions
=> support python 3.8 and 3.9

pyproject.toml, scripts/singularity_build.def
Closes #124 
- Adds lower bounds to packages to improve speed with installing packages
- Uses latest pip during singularity builds
=> fix: adds lower bounds on packages in pyproject.toml

src/aind_metadata_mapper/open_ephys/utils/stim_utils.py, src/aind_metadata_mapper/stimulus/camstim.py, tests/test_open_ephys/test_utils/test_stim_utils.py
Adds the ability to handle camstim projects which have their stim encoded using stim blocks within the ['stim'] field. Relatively simple change.
=> Feat handle camstim stim blocks

src/aind_metadata_mapper/bergamo/models.py, src/aind_metadata_mapper/bergamo/session.py, src/aind_metadata_mapper/bruker/models.py, src/aind_metadata_mapper/bruker/session.py, src/aind_metadata_mapper/core.py, src/aind_metadata_mapper/fip/models.py, src/aind_metadata_mapper/fip/session.py, src/aind_metadata_mapper/mesoscope/models.py, src/aind_metadata_mapper/mesoscope/session.py, src/aind_metadata_mapper/models.py, src/aind_metadata_mapper/open_ephys/camstim_ephys_session.py, src/aind_metadata_mapper/open_ephys/utils/behavior_utils.py, src/aind_metadata_mapper/open_ephys/utils/stim_utils.py, src/aind_metadata_mapper/smartspim/acquisition.py, src/aind_metadata_mapper/smartspim/models.py, src/aind_metadata_mapper/u19/models.py, src/aind_metadata_mapper/u19/procedures.py, tests/test_U19/test_procedures.py, tests/test_bergamo/test_session.py, tests/test_bruker/test_session.py, tests/test_core.py, tests/test_fip/test_session.py, tests/test_gather_metadata.py, tests/test_mesoscope/test_session.py, tests/test_open_ephys/test_rig.py, tests/test_smartspim/test_acquisition.py
Closes #143 
- Sets paths to optional paths or strings
- Has main etl jobs inherit common class to reduce duplicated code
- Marked this as a breaking change since I renamed a few fields that can be the same across all jobs settings. For example, I renamed `raw_data_path` in the SmartSPIM JobSettings to `input_source` via the parent class.
=> Feat 143 path strings

src/aind_metadata_mapper/gather_metadata.py, src/aind_metadata_mapper/models.py, tests/resources/gather_metadata_job/schema_files_with_issues/rig.json, tests/test_gather_metadata.py
Closes #159 
- Short-term patch to loosen restriction of pydantic validation and serialization. If a model json file is json serializable, we'll build the metadata record and flag the record as being invalid instead of raising an error and terminating the GatherMetadataJob
- Adds problematic rig.json in test folder
- Long-term, this logic should move to the aind-data-schema repo
=> Fix 159 rig json

pyproject.toml, tests/resources/dynamic_routing/base-missing-probe_rig.json, tests/resources/dynamic_routing/base_rig.json, tests/resources/open_ephys/open-ephys-inferred_rig.json, tests/resources/open_ephys/open-ephys_rig.json, tests/test_bergamo/test_session.py, tests/test_bruker/test_session.py, tests/test_dynamic_routing/test_mvr_rig.py, tests/test_dynamic_routing/test_sync_rig.py, tests/test_fip/test_session.py, tests/test_gather_metadata.py, tests/test_mesoscope/test_session.py, tests/test_open_ephys/test_rig.py
closes #182 
- Updates data-schema lower bound to 1.1.1
- Updates session from config test because the nested model_validation was breaking 
- Replaces schema_version in examples with model's default
=> pin to 1.1.1

src/aind_metadata_mapper/open_ephys/utils/stim_utils.py, tests/test_open_ephys/test_utils/test_stim_utils.py
This PR is intended to allow projects like OpenScopeTexture to correctly generate stimulus tables despite using images rather than movies for their stim
=> Support image based stimuli for camstim ephys sessions

src/aind_metadata_mapper/gather_metadata.py, tests/test_gather_metadata.py
Closes #198 
- Adds check if field is None, then set to empty string
- Removes inconsistent unit test breaking on pydantic serializer warnings
=> fix: patches bug parsing null funding field

src/aind_metadata_mapper/gather_metadata.py
Closes #213
- Removes check of metadata_dir_force flag
- Behavior is, if user supplies pre-compiled metadata file, then it assume that is the source of truth. If they did not supply one, then try to build one automatically.
=> feat: clarifies behavior of user metadata dir

pyproject.toml, src/aind_metadata_mapper/gather_metadata.py, tests/resources/gather_metadata_job/example_funding_multiple_response.json, tests/resources/gather_metadata_job/example_funding_response.json, tests/test_gather_metadata.py
Closes #225 
- Parses latest funding info schema
- Parses investigators from new investigators key instead of fundees key.
- Latest aind-data-schema v1.3.0 raises a bunch of errors. Added upper bound to version.
=> fix: parses latest funding schema

src/aind_metadata_mapper/open_ephys/utils/behavior_utils.py, src/aind_metadata_mapper/open_ephys/utils/pkl_utils.py
This removes decoding of type "bytes" for the img pickle path that is pointed toward by the behavior pickle file. Tested using '/allen/programs/mindscope/production/openscope/prod0/specimen_1400574834/ophys_session_1417115172/1417115172.pkl' and '/allen/programs/mindscope/production/openscope/prod0/specimen_1400574834/ophys_session_1417115172/1417115172_20250129T094614.h5' and confirmed that the old bytes error does not occur any longer.
Resolves #234
=> Bug fix/remove byte decoding

src/aind_metadata_mapper/open_ephys/utils/pkl_utils.py, src/aind_metadata_mapper/stimulus/camstim.py, tests/test_mesoscope/test_session.py, tests/test_open_ephys/test_utils/test_pkl_utils.py, tests/test_stimulus/test_camstim.py
Uses the PKL for stage name and disregards the optional URL field to avoid mtrain query errors.
=> Bug fix/avoid mtrain stage url

README.md
Fix installation commands to work in zsh
Add quotes around pip install arguments to prevent zsh from interpreting square brackets as pattern matching characters. This maintains compatibility across all shells while fixing the installation issue for zsh users (default shell on macOS).
closes #260
=> Fixed install instructions

scripts/example_create_fiber_and_pav_sessions.py
I failed to update the imports in the example creation script after a last minute change in #250. This PR fixes that issue. Also updates the example in the docstring to use a better naming convention. 
Verified I can now successfully run:
```bash
% python scripts/example_create_fiber_and_pav_sessions.py \
--subject-id "000000" \
--behavior-dir data/sample_fiber_data/behavior \
--fiber-dir data/sample_fiber_data/fib \
--output-dir data/sample_fiber_data \
--experimenters "Test User 1" "Test User 2" \
--behavior-output "session_pavlovian.json" \
--fiber-output "session_fib.json" \
--merged-output "session.json"
```
=> Fixed imports in example combined fib+beh session creation script

scripts/example_create_fiber_and_pav_sessions.py
The original code was mainly designed to be used with CLI/argparse as a command-line function. I foresee a need to use it as a standalone python function too. So, this refactoring introduced the `create_unified_session_metadata()` while keeping the `main()` function at the bottom so it can be used for both use cases.
=> suggestion for the example code to make it a python function

pyproject.toml
Pins wavpack-numcodecs to 0.2.2 (latest version 0.2.3 fails to build with docker image version)
=> pins wavpack-numcodecs

src/aind_metadata_mapper/gather_metadata.py, tests/test_gather_metadata.py
- Removes CamstimEtl from gather_metadata_job as a quick workaround for:
https://github.com/AllenNeuralDynamics/aind-metadata-mapper/issues/328
- Adds additional tests to get coverage to 80%
- Runs isort and black on gather_metadata_job module
=> fix: excludes camstim from gathermetadata job

src/aind_metadata_mapper/gather_metadata.py, tests/test_gather_metadata.py
Closes #345 
- Uses `requests.Session` object with retries to get data from metadata service.
- Raises an error if metadata service returns a server error response when fetching procedures metadata
=> feat: adds rety logic to metadata service requests
